triggers:
  - trigger: state
    entity_id:
      - binary_sensor.ajtonyitas
    from: "off"
    to: "on"
conditions:
  - condition: state
    entity_id: person.apa
    state: home
  - condition: template
    value_template: >-
      {{(as_timestamp(now()) -
      as_timestamp(states.person.apa.last_changed)) < 300 }}

actions:
